const level1 = new Level (
    [
        new Chicken (),
        new Chicken (),
        new Chicken (),
        new Chicken (),
        new Chicken (),
        new Chicken (),
        new Chicken (),
        new Endboss(),
        new BigChicken (),
        new BigChicken (),
        new BigChicken (),
        new BigChicken (),
        new BigChicken (),
        new BigChicken (),
    ],
    [
        new Cloud (),
        new Cloud (),
        new Cloud (),
        new Cloud (),
        new Cloud (),
        new Cloud (),
        new Cloud (),
        new Cloud (),
        new Cloud (),
    ],
    [
        new BackgroundObject('./img/5_background/layers/air.png', -749),
        new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', -749),
        new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', -749),
        new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', -749),

        new BackgroundObject('./img/5_background/layers/air.png', 0),
        new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 0),

        new BackgroundObject('./img/5_background/layers/air.png', 749),   
        new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 749),
        new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 749),
        new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 749),

        new BackgroundObject('./img/5_background/layers/air.png', 749*2),
        new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 749*2),
        new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 749*2),
        new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 749*2),

        new BackgroundObject('./img/5_background/layers/air.png', 749*3),
        new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 749*3),
        new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 749*3),
        new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 749*3),

        new BackgroundObject('./img/5_background/layers/air.png', 749*4),
        new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 749*4),
        new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 749*4),
        new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 749*4),

        new BackgroundObject('./img/5_background/layers/air.png', 749*5),
        new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 749*5),
        new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 749*5),
        new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 749*5),

        new BackgroundObject('./img/5_background/layers/air.png', 749*6),
        new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 749*6),
        new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 749*6),
        new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 749*6),
    ],
    [
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
        new CollectableObjectCoins (),
    ],
    [
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
        new CollectableObjectBottles (),
    ],
);